---
receivers:
  otlp:
    protocols:
      http:
        endpoint: :4318
exporters:
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
  debug:
    verbosity: detailed
processors:
  batch:
extensions:
  health_check:
    endpoint: :13133
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, zipkin]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
